---
# It's important that we don't explicitly pull this image here.  Otherwise we
# could result in upgrading a preinstalled environment.  We'll have to set
# openshift_image_tag correctly for upgrades.
- set_fact:
    is_containerized: "{{ openshift.common.is_containerized | default(False) | bool }}"
    # Does the host already have an image tag fact, used to determine if it's a new node
    # in non-upgrade scenarios:
    has_image_tag_fact: "{{ hostvars[inventory_hostname].openshift.docker.openshift_image_tag is defined }}"

- name: Set version when containerized
  command: >
    docker run --rm {{ openshift.common.cli_image }} version
  register: cli_image_version
  when: is_containerized | bool and openshift_image_tag is not defined and (upgrading | bool or not has_image_tag_fact | bool)

# Use the pre-existing image tag from system facts if present, and we're not upgrading.
# Ignores explicit openshift_image_tag if it's in the inventory, as this isn't an upgrade.
- set_fact:
    l_image_tag: "{{ hostvars[inventory_hostname].openshift.docker.openshift_image_tag }}"
  when: is_containerized | bool and not upgrading | bool and has_image_tag_fact | bool

- set_fact:
    l_image_tag: "{{ cli_image_version.stdout_lines[0].split(' ')[1].split('-')[0:2] | join('-') if openshift.common.deployment_type == 'origin' else
                     cli_image_version.stdout_lines[0].split(' ')[1].split('-')[0] }}"
  when: is_containerized | bool and openshift_image_tag is not defined and (upgrading | bool or not has_image_tag_fact | bool)

- set_fact:
    l_image_tag: "{{ openshift_image_tag }}"
  when: is_containerized | bool and openshift_image_tag is defined and (upgrading | bool or not has_image_tag_fact | bool)

- name: Set post docker install facts
  openshift_facts:
    role: "{{ item.role }}"
    local_facts: "{{ item.local_facts }}"
  with_items:
  - role: docker
    local_facts:
      openshift_image_tag: "{{ l_image_tag | default(None) }}"
      openshift_version: "{{ l_image_tag.split('-')[0] | oo_image_tag_to_rpm_version if l_image_tag is defined else '' }}"
  when: is_containerized | bool
