---
galaxy_info:
  author: Jason DeTiberus
  description: OpenShift Master Certificates
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 1.9.4
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
  - system
dependencies:
- role: openshift_ca
