---
- name: Install flannel
  become: yes
  action: "{{ ansible_pkg_mgr }} name=flannel state=present"
  when: not openshift.common.is_containerized | bool

- name: Set flannel etcd url
  become: yes
  lineinfile:
    dest: /etc/sysconfig/flanneld
    backrefs: yes
    regexp: "^(FLANNEL_ETCD=)"
    line: '\1{{ etcd_hosts|join(",") }}'

- name: Set flannel etcd key
  become: yes
  lineinfile:
    dest: /etc/sysconfig/flanneld
    backrefs: yes
    regexp: "^(FLANNEL_ETCD_KEY=)"
    line: '\1{{ flannel_etcd_key }}'

- name: Set flannel options
  become: yes
  lineinfile:
    dest: /etc/sysconfig/flanneld
    backrefs: yes
    regexp: "^#?(FLANNEL_OPTIONS=)"
    line: '\1--iface {{ flannel_interface }} --etcd-cafile={{ etcd_peer_ca_file }} --etcd-keyfile={{ etcd_peer_key_file }} --etcd-certfile={{ etcd_peer_cert_file }}'

- name: Enable flanneld
  become: yes
  service:
    name: flanneld
    state: started
    enabled: yes
  register: start_result

- name: Remove docker bridge ip
  become: yes
  shell: ip a del `ip a show docker0 | grep "inet[[:space:]]" | awk '{print $2}'` dev docker0
  notify:
    - restart docker
    - restart node
